spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp 
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/lolBuild?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: caslfrokflgzpwan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.sbs.kig.lolBuild.dto
  
custom:
  siteName: 롤 템트리 빌드 
  siteMainUri: http://localhost:8051/usr/home/main
  logoText: 롤 템트리 빌드
  emailFrom: no-reply@lolBuild.com
  emailFromName: 롤 템트리 빌드

---

spring:
  profiles: local
server:
  port: 8051  

---
spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: lolBuild
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lolBuild?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
